### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by GiuseppeMP** [nvim-neotest/neotest-vim-test#4]
After the lasties updates in vim-test or neotest idk, all my projects using .java in all neotest commands, now returns "No tests found".

Obs: `vim-test` commands are working well.

I'm back to the vim-test commands meanwhile.

**Comment by rcarriga** [comment]
I'm not at all familiar with Java, could you point me to a repo that I can test in? Also could you provide any vim-test related settings you're using?

**Comment by GiuseppeMP** [comment]
@rcarriga I created this project for testing neotest: https://github.com/GiuseppeMP/examples-java-junit-jupiter-api

My config: https://github.com/GiuseppeMP/my-nvim-config/blob/main/lua/user/plugins/configs/neotest.lua

**Comment by rcarriga** [comment]
I'm afraid that works perfectly fine for me locally. Can you provide a fresh debug log as described in this bug report template https://github.com/nvim-neotest/neotest/issues/new?assignees=rcarriga&labels=&template=bug_report.md&title=%5BBUG%5D. If there's nothing of note in them I'll need a minimal init.lua to reproduce
