### ISSUE TITLE
it broke after neotest updates to 3.0.0

### ISSUE THREAD

**Issue by GiuseppeMP** [nvim-neotest/neotest-vim-test#5]
@rcarriga 

After updated neotest to 3.0.0, the neotest-vim-test adapter broke with the error:

`neotest-vim-test/init.lua:166: attempt to index field 'Semaphore' (a nil value)`

Am I need to change something in the setup because of the new async impl?

**Comment by weslenbreno** [comment]
I'm having the same issue

**Comment by tubzby** [comment]
Same issue here.

**Comment by rcarriga** [comment]
Thanks for the report! I've updated the adapter to the new changes

**Comment by tubzby** [comment]
Thanks for your kind work! @rcarriga
